
print("%8s" % 'A')
print("%7s%2s" % ('B', "B"))
print("%6s%4s" % ('C', "C"))
print("%5s%6s" % ('D', "D"))
print("%4s%8s" % ('E', "E"))
print("%5s%6s" % ('D', "D"))
print("%6s%4s" % ('C', "C"))
print("%7s%2s" % ('B', "B"))
print("%8s" % 'A')
